language: java
jdk:
- oraclejdk8
- openjdk7
install: mvn install -Dgpg.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - FIGO_API_FINGERPRINTS=D0:03:9E:F0:8F:BD:48:67:86:71:CE:9D:A5:54:24:81:63:D7:D9:4D:ED:F1:6A:55:F0:52:C7:0A:AB:7B:B8:9D
  - FIGO_API_ENDPOINT=https://api.figo.me
  - secure: Q3pesvOpVY0dYif+rxgd8Ae7INqgRioGW+aC3pCMmiQVVNmk1qY+CllX3/k4tx47R33pYz9NR3tU8wDfp6HmCrlh+LeLKtcGkrEyjBkx5g8lQWPxKo8EY2pRAVOqtrHLVlsPZlyfj3fMjrlzidVw4fnZB1/+gOYoMeMwrv/RPrU=
  - secure: jXjULM4iyEFlQZjNSztq0ETftXX3NdtCB3KW2KJ3PLfCsrE7jEs7FAZ/65CApk/6AQmWtkg8sPyZVyU6eAOY4Fn17mfYXNMQKTRAi9yXLN7sQGelOrhZARIJLq1sEih9DKOlOXMFvbxN422gTtO7N/+Xo+2vFYBeezPw44pt+UA=
