language: java
jdk:
- oraclejdk8
- openjdk7
install: mvn install -Dgpg.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script: mvn test
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: W2HckgOHtFN6nng1si0szxVOlCTNEZPBsfxoI7uDe4x/C4ZQCTBFO7pLbWj0emNQQVGjlXOvKXwTfhaEN6OdWN7HBybwEj90hQsf4zKvVXfiqb0VA+VtKWM1lWDvWv4EqSh+7FybA5wQmWM2LgA77NyxabRJ8PmR8G+BEMAXhG0=
  - secure: BR4XpTwfXf7j9r9UgEiK4Ao38dWBf14VbaNqyDMmImPOTrfq7o+wJrlG9aTWw//naBaetmlD1PUtPxrxgk4F/+4/rZu87STcsQApnhO28bQ76IOovgtffOEiWgQMVMxJBdPqJeKwgY9ZYQMKWz+pySn6Oj5r/qHcIttGEmigTOM=
  - secure: Ya+F562g0HN3gNMCXbC2ClPxzhTfX4dr+hchRm4J1yLuUDktlFDIFp07qa0BvPWdRrd2mV86rsl7UmHYxP3KIyD0NhoCuUjw2gVNfOgxEHw+J/U13regg1Wvx8UbQkbvEnQESKBLHaFdAh/BVjxRqNu4zIPNjU/LnufIs+8HliM=
  - secure: UYvlMxgW7bwu741x3ptz8KRVUZV9Kl7EgWYBzWEK0Rf5XapTy+SqB1nQAxxtP/GWZAss3EQQetDln7GtDk4W5QIffMnme9JJqwVXrKdiC0b6k3O8R38JLEIYf2RI69E1p/D1xN1zzZv1jQg1EZQ7Mw8gtD7+Rd+oaak84hRTtxY=
  - secure: PxoX2p4H6pJn5EF9+45u8THV+bgFg1T03dYvANoR73/h+r4C+buDmt1UBjnT2j1+vxaTsSLMHKD2+8k9luB9Mw+8qFiF1pHAH6NF1FZvqS3Q17I/1ZNotDCkg50xm4Kg0UAdLLTVFeVrXKvK3Iyr2kKhxMLSZVa3OlEz2PT+ziM=
  - FIGO_API_FINGERPRINTS=D0039EF08FBD48678671CE9DA554248163D7D94DEDF16A55F052C70AAB7BB89D
  - FIGO_API_ENDPOINT=https://api.figo.me
  - secure: Q3pesvOpVY0dYif+rxgd8Ae7INqgRioGW+aC3pCMmiQVVNmk1qY+CllX3/k4tx47R33pYz9NR3tU8wDfp6HmCrlh+LeLKtcGkrEyjBkx5g8lQWPxKo8EY2pRAVOqtrHLVlsPZlyfj3fMjrlzidVw4fnZB1/+gOYoMeMwrv/RPrU=
  - secure: jXjULM4iyEFlQZjNSztq0ETftXX3NdtCB3KW2KJ3PLfCsrE7jEs7FAZ/65CApk/6AQmWtkg8sPyZVyU6eAOY4Fn17mfYXNMQKTRAi9yXLN7sQGelOrhZARIJLq1sEih9DKOlOXMFvbxN422gTtO7N/+Xo+2vFYBeezPw44pt+UA=
  - secure: PxoX2p4H6pJn5EF9+45u8THV+bgFg1T03dYvANoR73/h+r4C+buDmt1UBjnT2j1+vxaTsSLMHKD2+8k9luB9Mw+8qFiF1pHAH6NF1FZvqS3Q17I/1ZNotDCkg50xm4Kg0UAdLLTVFeVrXKvK3Iyr2kKhxMLSZVa3OlEz2PT+ziM=
